title: Continuously Me
description: Just Me Being Me. Continuously.
google_analytics:
show_downloads: false
theme: jekyll-theme-midnight
paginate: 3

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-mentions
  - jekyll-paginate
